---
apiVersion: v1
kind: Secret
metadata:
  name: karpenter-template
  namespace: kube-system
stringData:
  network-config: |
    network:
      version: 2
      ethernets:
    {{- range .Interfaces }}
        {{ .Name }}:
          match:
            macaddress: {{ .MacAddr | lower | quote }}
          dhcp4: true
          dhcp6: false
    {{- if ne .MTU 0 }}
          mtu: {{ .MTU }}
    {{- end }}
    {{- end }}
  user-data: |
    #cloud-config
    hostname: {{ .Metadata.Hostname }}
    manage_etc_hosts: true

    users:
      - name: alpine
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/ash
        lock_passwd: false{{- with get .Values "SSHAuthorizedKeys" }}
        ssh_authorized_keys:{{- range (split . ",") }}
          - {{ . }}{{- end }}{{- end }}

    write_files:
      - path: /usr/local/bin/join-k3s.sh
        permissions: '0755'
        content: |
          #!/bin/sh
          set -e
          INSTALL_K3S_VERSION="{{ get .Values "K3sVersion" }}" \
          K3S_URL="{{ get .Values "K3sURL" }}" \
          K3S_TOKEN="{{ get .Values "K3sToken" }}" \
          INSTALL_K3S_SKIP_DOWNLOAD=false \
          sh /usr/local/bin/k3s-install.sh \
            --kubelet-arg "provider-id={{ .Metadata.ProviderID }}" \
            --kubelet-arg "register-with-taints=karpenter.sh/unregistered:NoExecute" \
            --kubelet-arg "cloud-provider=external"

    runcmd:
      - swapoff -a
      - curl -fsSL https://get.k3s.io -o /usr/local/bin/k3s-install.sh
      - chmod +x /usr/local/bin/k3s-install.sh
      - /usr/local/bin/join-k3s.sh
      - rc-update add k3s-agent default
