apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karpenter-provider-proxmox.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-provider-proxmox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
  selector:
    matchLabels:
      {{- include "karpenter-provider-proxmox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if .Values.config }}
        checksum/config: {{ toJson .Values.config | sha256sum }}
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "karpenter-provider-proxmox.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "karpenter-provider-proxmox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers: {{- toYaml .Values.initContainers | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -cloud-config=/etc/proxmox/config.yaml
            - -log-level={{ .Values.logVerbosityLevel }}
            - -leader-election-name=proxmox-karpenter-leader-election
          {{- if .Values.metrics.enabled }}
            - -metrics-port=8080
          {{- end }}
            - -health-probe-port=8081
          {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- with .Values.extraEnvs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.metrics.enabled }}
            - name: METRICS_PORT
              value: "{{ .Values.metrics.port }}"
          {{- end }}
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: {{ .Chart.Name }}
                  divisor: "0"
                  resource: limits.memory
            - name: FEATURE_GATES
              value: "ReservedCapacity={{ .Values.settings.featureGates.reservedCapacity }},SpotToSpotConsolidation={{ .Values.settings.featureGates.spotToSpotConsolidation }},NodeRepair={{ .Values.settings.featureGates.nodeRepair }}"
          {{- with .Values.settings.batchMaxDuration }}
            - name: BATCH_MAX_DURATION
              value: "{{ tpl (toString .) $ }}"
          {{- end }}
          {{- with .Values.settings.batchIdleDuration }}
            - name: BATCH_IDLE_DURATION
              value: "{{ tpl (toString .) $ }}"
          {{- end }}
          {{- with .Values.settings.preferencePolicy }}
            - name: PREFERENCE_POLICY
              value: "{{ . }}"
          {{- end }}
          {{- with .Values.settings.minValuesPolicy }}
            - name: MIN_VALUES_POLICY
              value: "{{ . }}"
          {{- end }}
          {{- with .Values.settings.vmMemoryOverheadPercent }}
            - name: VM_MEMORY_OVERHEAD_PERCENT
              value: "{{ tpl (toString .) $ }}"
          {{- end }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: 8080
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cloud-config
              mountPath: /etc/proxmox
              readOnly: true
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- else }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "karpenter-provider-proxmox.selectorLabels" . | nindent 20 }}
                topologyKey: topology.kubernetes.io/zone
              weight: 1
      {{- end }}
      tolerations:
      {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "karpenter-provider-proxmox.selectorLabels" . | nindent 14 }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if .Values.existingConfigSecret }}
        - name: cloud-config
          secret:
            secretName: {{ .Values.existingConfigSecret }}
            items:
              - key: {{ .Values.existingConfigSecretKey }}
                path: config.yaml
            defaultMode: 416
        {{- else }}
        - name: cloud-config
          secret:
            secretName: {{ include "karpenter-provider-proxmox.fullname" . }}
            defaultMode: 416
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
