apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "karpenter-provider-proxmox.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-provider-proxmox.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - patch
  - update
  resourceNames:
  - proxmox-karpenter-leader-election
# Metadata templates options
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  resourceNames:
  - kube-root-ca.crt
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "karpenter-provider-proxmox.fullname" . }}:bootstrap
  namespace: kube-system
  labels:
    {{- include "karpenter-provider-proxmox.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
