---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  limits:
    cpu: "64"
    memory: 512Gi
  template:
    spec:
      nodeClassRef:
        group: karpenter.proxmox.sinextra.dev
        kind: ProxmoxNodeClass
        name: default
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        # - key: "karpenter.proxmox.sinextra.dev/instance-family"
        #   operator: In
        #   values: ["c1"]
        # - key: "karpenter.sh/capacity-type"
        #   operator: In
        #   values: ["spot", "on-demand", "reserved"]
        # - key: "topology.kubernetes.io/zone"
        #   operator: In
        #   values: ["rnd-1", "rnd-2"]
---
apiVersion: karpenter.proxmox.sinextra.dev/v1alpha1
kind: ProxmoxNodeClass
metadata:
  name: default
spec:
  # region: region-2
  # placementStrategy:
  #   zoneBalance: AvailabilityFirst
  instanceTemplateRef:
    kind: ProxmoxUnmanagedTemplate
    # kind: ProxmoxTemplate
    name: default
  metadataOptions:
    type: cdrom
    templatesRef:
      name: talos-template
      namespace: kube-system
    valuesRef:
      name: talos-values
      namespace: kube-system
  kubeletConfiguration:
    allowedUnsafeSysctls: [net.core.somaxconn]
    topologyManagerPolicy: best-effort
  bootDevice:
    size: 30Gi
    storage: zfs
  securityGroups:
    - name: kubernetes
      interface: net0
  tags:
    - talos-k8s-proxmox
    - karpenter
    # - test
