---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  limits:
    cpu: "64"
    memory: 512Gi
  template:
    spec:
      nodeClassRef:
        group: karpenter.proxmox.sinextra.dev
        kind: ProxmoxNodeClass
        name: default
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
---
apiVersion: karpenter.proxmox.sinextra.dev/v1alpha1
kind: ProxmoxNodeClass
metadata:
  name: default
spec:
  instanceTemplateRef:
    kind: ProxmoxUnmanagedTemplate
    name: talos
  metadataOptions:
    type: cdrom
    templatesRef:
      name: karpenter-template
      namespace: kube-system
    valuesRef:
      name: karpenter-template-values
      namespace: kube-system
  bootDevice:
    size: 30Gi
